// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOJZiomrs2PE0d2Qgw3e7IoWwOttohpA4',
    appId: '1:508285471344:web:d0a29e81e167c727abc2b5',
    messagingSenderId: '508285471344',
    projectId: 'chatfixhub',
    authDomain: 'chatfixhub.firebaseapp.com',
    storageBucket: 'chatfixhub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5vycYeGWUviA6YX6yRH8FHQqEVfLPbo',
    appId: '1:508285471344:android:f449bd2a11b021f5abc2b5',
    messagingSenderId: '508285471344',
    projectId: 'chatfixhub',
    storageBucket: 'chatfixhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWqU1K1oKTUlr9EQiY5lh6DADw6hqOgg',
    appId: '1:508285471344:ios:868414dff2e00ec7abc2b5',
    messagingSenderId: '508285471344',
    projectId: 'chatfixhub',
    storageBucket: 'chatfixhub.firebasestorage.app',
    iosBundleId: 'com.example.fixHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWqU1K1oKTUlr9EQiY5lh6DADw6hqOgg',
    appId: '1:508285471344:ios:868414dff2e00ec7abc2b5',
    messagingSenderId: '508285471344',
    projectId: 'chatfixhub',
    storageBucket: 'chatfixhub.firebasestorage.app',
    iosBundleId: 'com.example.fixHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOJZiomrs2PE0d2Qgw3e7IoWwOttohpA4',
    appId: '1:508285471344:web:4da7a489100f2738abc2b5',
    messagingSenderId: '508285471344',
    projectId: 'chatfixhub',
    authDomain: 'chatfixhub.firebaseapp.com',
    storageBucket: 'chatfixhub.firebasestorage.app',
  );
}
